name: CI

on:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Generates SBOM
        id: generatesSBOM
        run: composer install && composer make-bom --output-format=json
      - name: Prints SBOM
        run: |
          curl -X "POST" "http://159.89.100.172:8081/api/v1/bom" \
            -H 'X-API-Key: ${{ secrets.SECRET_OWASP_DT_KEY }}' \
            -F "project=fa210568-6e59-414b-94f2-e135100125a5" \
            -F "bom=@bom.json"
      - name: Fetch results from production
        run: |
          curl -X "GET" "http://159.89.100.172:8081/api/v1/metrics/project/172a294c-a014-4c9d-afe8-27dc12be533e/current" \
            -H 'X-API-Key: ${{ secrets.SECRET_OWASP_DT_KEY }}' -o metrics-prod.json
      - name: Fetch results from dev
        run: |
          curl -X "GET" "http://159.89.100.172:8081/api/v1/metrics/project/fa210568-6e59-414b-94f2-e135100125a5/current" \
            -H 'X-API-Key: ${{ secrets.SECRET_OWASP_DT_KEY }}' -o metrics-dev.json      
      - name: Check for vulnerabilities on production
        id: check-production
        run: |
          echo "RESULTS=$(cat metrics-prod.json | jq '.vulnerabilities')" >> $GITHUB_OUTPUT
      - name: Check for new vulns
        id: check-dev
        run: |
          echo "RESULTS=$(cat metrics-dev.json | jq '.vulnerabilities')" >> $GITHUB_OUTPUT
      - name: Put a comment
        uses: thollander/actions-comment-pull-request@v1
        if: steps.check-dev.outputs.RESULTS > steps.check-prod.outputs.RESULTS
        with:
          message: |-
            You introduced new vulnerabilities!
