name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Generates SBOM
        id: generatesSBOM
        run: composer make-bom --output-format=json
      - name: Generates base64
        id: generatesBase64
        run: |
          curl -X "PUT" "http://68.183.76.99:8080/api/v1/bom" \
            -H 'Content-Type: application/json' \
            -H 'X-API-Key: ${{ secrets.SECRET_OWASP_DT_KEY }}' \
            -F "project=97b4a155-0f30-4d74-a619-c3aaf7c215eb" \
            -F "bom=@bom.json"
      - name: Print bom
        if: success() || failure()
        shell: bash
        run: |
          value=`cat bom.xml`
          echo The result is $value
      - name: Get the output time
        run: echo "The risk score of the project is ${{ steps.riskscoreFromDT.outputs.riskscore }}"
