name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Generates SBOM
        id: generatesSBOM
        run: composer install && composer make-bom --output-format=json
      - name: Prints SBOM
        run: |
          curl -X "POST" "http://68.183.76.99:8081/api/v1/bom" \
            -H 'X-API-Key: ${{ secrets.SECRET_OWASP_DT_KEY }}' \
            -F "project=428549e2-6e63-40b5-b84e-3ecebfa865fd" \
            -F "bom=@bom.json"
