name: Dependency-Track-Dev

on:
  push:
    paths:
      - 'composer.lock'
      - '.github/workflows/owasp-dt-check.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      # Add cyclonedx plugin and install it
      - name: Install Cyclonedx
        id: installsCyclonedx
        run: composer global config --no-plugins allow-plugins.cyclonedx/cyclonedx-php-composer true && composer global require --ignore-platform-reqs --dev cyclonedx/cyclonedx-php-composer
      - name: Generate SBOM
        id: generatesSBOM
        run: composer make-bom --output-format=json
      # Send SBOM to dev project
      - name: Prints SBOM
        id: printsSBOM
        run: |
          echo "RESULTS=$(curl -X "POST" "http://159.89.100.172:8081/api/v1/bom" \
            -H 'X-API-Key: ${{ secrets.SECRET_OWASP_DT_KEY }}' \
            -F "project=2c0dfba2-335d-4723-8e07-eeef5baa3386" \
            -F "bom=@bom.json" | jq '.token' | sed 's/\"//g')" >> $GITHUB_OUTPUT
      - name: Fetch results from production
        id: check-prod
        run: |
          echo "RESULTS=$(curl -X "GET" "http://159.89.100.172:8081/api/v1/metrics/project/3750aaa5-b4b5-4d7d-9818-231ce07927d5/current" \
            -H 'X-API-Key: ${{ secrets.SECRET_OWASP_DT_KEY }}' | jq '.vulnerabilities')" >> $GITHUB_OUTPUT
      - name: Check if still processed
        id: check-processing
        run: |
          echo "RESULTS=$(curl -X "GET" "http://159.89.100.172:8081/api/v1/bom/token/${{ steps.printsSBOM.outputs.RESULTS }}" -H 'X-API-Key: ${{ secrets.SECRET_OWASP_DT_KEY }}' | jq '.processing')" >> $GITHUB_OUTPUT
      - name: Wait for processing
        if: ${{ steps.check-processing.outputs.RESULTS }} == "true"
        run: sleep 5s
      - name: Fetch results from dev
        id: check-dev
        run: |
          echo "RESULTS=$(curl -X "GET" "http://159.89.100.172:8081/api/v1/metrics/project/2c0dfba2-335d-4723-8e07-eeef5baa3386/current" \
            -H 'X-API-Key: ${{ secrets.SECRET_OWASP_DT_KEY }}' | jq '.vulnerabilities')" >> $GITHUB_OUTPUT
      - name: Debug
        run: echo ${{ steps.check-dev.outputs.RESULTS }} && echo ${{ steps.check-prod.outputs.RESULTS }} && echo ${{ steps.check-processing.outputs.RESULTS }}
      - name: Add commit comment
        if: steps.check-dev.outputs.RESULTS  > steps.check-prod.outputs.RESULTS
        run: |
          jq -nc '{"body": "It looks like you updated dependencies files and it resulted with adding vulnerable library. Please review the dependencies you added. You can see the vulnerabilities details [here](http://159.89.100.172:8080/projects/a8d7eabb-4ea6-4b0b-900a-3e62db2cb622). You can login with AWS SSO. "}' | \
          curl -sL  -X POST -d @- \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/comments"
